const SAMPLE_IMAGES = [
  "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
  "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600&q=80",
  "https://images.unsplash.com/photo-1607582544363-c4a4ac9eecc7?w=600&q=80",
  "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=600&q=80",
  "https://images.unsplash.com/photo-1543342384-1f1350e27861?w=600&q=80",
];

export const GENDER_OPTIONS = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Other", label: "Other" },
];


export const STATUS_OPTIONS = [
  { value: "Active", label: "Active" },
  { value: "Enrolled", label: "Enrolled" },
];


export const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

export const mockChildrenList = [
  {
    id: "ch1",
    firstName: "adil",
    lastName: "ali",
    image: SAMPLE_IMAGES[0],
    dob: "2023-01-02",
    joinedAt: "2026-04-08",
    code: "306",
    gender: "male",
    status: "active",
    centreId: "c1",
    roomId: "r2",
    roomName: "test by apk",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  },
  {
    id: "ch2",
    firstName: "test by apk",
    lastName: "test",
    image: SAMPLE_IMAGES[1],
    dob: "2022-05-11",
    joinedAt: "2025-05-06",
    code: "155",
    gender: "male",
    status: "active",
    centreId: "c1",
    roomId: "r2",
    roomName: "test by apk",
    days: ["Monday", "Wednesday", "Friday"],
  },
  {
    id: "ch3",
    firstName: "test1",
    lastName: "tst",
    image: SAMPLE_IMAGES[2],
    dob: "2002-03-29",
    joinedAt: "2025-03-13",
    code: "118",
    gender: "male",
    status: "active",
    centreId: "c1",
    roomId: "r1",
    roomName: "test",
    days: ["Tuesday", "Thursday"],
  },
  {
    id: "ch4",
    firstName: "testchild1",
    lastName: "test",
    image: SAMPLE_IMAGES[3],
    dob: "2023-06-06",
    joinedAt: "2025-09-01",
    code: "230",
    gender: "male",
    status: "active",
    centreId: "c1",
    roomId: "r2",
    roomName: "test by apk",
    days: ["Monday", "Tuesday", "Wednesday"],
  },
  {
    id: "ch5",
    firstName: "testchild3",
    lastName: "test3",
    image: SAMPLE_IMAGES[4],
    dob: "2021-05-03",
    joinedAt: "2024-08-20",
    code: "232",
    gender: "female",
    status: "active",
    centreId: "c1",
    roomId: "r1",
    roomName: "test",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  },
  {
    id: "ch6",
    firstName: "Sophia",
    lastName: "Anderson",
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600&q=80",
    dob: "2022-11-12",
    joinedAt: "2025-02-10",
    code: "401",
    gender: "female",
    status: "inactive",
    centreId: "c2",
    roomId: "r4",
    roomName: "Sunflower",
    days: ["Monday", "Wednesday"],
  },
];