import {
  LayoutDashboard,
  CalendarDays,
  NotebookPen,
  BookOpen,
  ShieldPlus,
  Moon,
  ClipboardPlus,
  GraduationCap,
  ClipboardList,
  BarChart3,
  PencilLine,
  SlidersHorizontal,
  Camera,
  Building2,
  DoorOpen,
  Users2,
  Megaphone,
  Info,
  UtensilsCrossed,
  ChefHat,
  BookOpenCheck,
  Salad,
  ShieldCheck,
  ListChecks,
  FileText,
  Settings,
  CalendarCheck,
  Monitor,
  Building,
  UserCog,
  KeyRound,
  ShieldAlert,
  Users,
} from "lucide-react";

export const navConfig = [
  {
    key: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    to: "/dashboard",
  },
  {
    key: "daily-operations",
    label: "Daily Operations",
    icon: CalendarDays,
    items: [
      { label: "Daily Diary", to: "/daily-diary", icon: BookOpen },
      { label: "Head Check", to: "/head-check", icon: ShieldPlus },
      { label: "Sleep Check", to: "/sleep-check", icon: Moon },
      { label: "Accident Form", to: "/accident-form", icon: ClipboardPlus },
    ],
  },
  {
    key: "learning",
    label: "Learning & Documentation",
    icon: GraduationCap,
    items: [
      { label: "Program Plan", to: "/program-plan", icon: ClipboardList },
      { label: "Learning & Progress", to: "/learning-progress", icon: BarChart3 },
      { label: "Daily Reflections", to: "/daily-reflections", icon: PencilLine },
      { label: "Observation", to: "/observation", icon: SlidersHorizontal },
      { label: "Snapshots", to: "/snapshots", icon: Camera },
    ],
  },
  {
    key: "centre",
    label: "Centre Management",
    icon: Building2,
    items: [
      { label: "Rooms", to: "/rooms", icon: DoorOpen },
      { label: "Children", to: "/children", icon: Users2 },
      { label: "Events", to: "/events", icon: Megaphone },
      { label: "Service Details", to: "/service-details", icon: Info },
    ],
  },
  {
    key: "nutrition",
    label: "Nutrition",
    icon: UtensilsCrossed,
    items: [
      { label: "Menu", to: "/menu", icon: ChefHat },
      { label: "Recipe", to: "/recipe", icon: BookOpenCheck },
      { label: "Ingredients", to: "/ingredients", icon: Salad },
    ],
  },
  {
    key: "compliance",
    label: "Quality & Compliance",
    icon: ShieldCheck,
    items: [
      { label: "QIP", to: "/qip", icon: ListChecks },
      { label: "Forms", to: "/forms", icon: FileText },
      { label: "PTM", to: "/ptm", icon: CalendarCheck },
    ],
  },
  {
    key: "admin",
    label: "Administration",
    icon: Settings,
    items: [
      { label: "IP Management", to: "/ip-management", icon: Monitor },
      { label: "Center Settings", to: "/settings", icon: Building },
      { label: "Staff Settings", to: "/staff-settings", icon: UserCog },
      // { label: "Super Admin Settings", to: "/super-admin-settings", icon: ShieldAlert },
      { label: "Parent Settings", to: "/parent-settings", icon: Users },
      { label: "Manage Permissions", to: "/permissions", icon: KeyRound },
    ],
  },
];
