/** Display labels for nature checkboxes. Keep these aligned with the paper form. */
export const NATURE_OPTIONS = [
  "Abrasion / scrape",
  "Allergic reaction (not anaphylaxis)",
  "Amputation",
  "Anaphylaxis",
  "Asthma / respiratory",
  "Bite wound",
  "Bruise",
  "Broken bone / fracture / dislocation",
  "Burn / sunburn",
  "Choking",
  "Concussion",
  "Crush / jam",
  "Cut / open wound",
  "Drowning (non-fatal)",
  "Electric shock",
  "Eye injury",
  "Infectious disease (incl. gastrointestinal)",
  "High temperature",
  "Ingestion / inhalation / insertion",
  "Internal injury / infection",
  "Poisoning",
  "Rash",
  "Respiratory",
  "Seizure / unconscious / convulsion",
  "Sprain / swelling",
  "Stabbing / piercing",
  "Tooth",
  "Venomous bite / sting",
  "Other (please specify)",
];

/** Maps display label -> API field name for save/load. */
export const NATURE_API_MAP = {
  "Abrasion / scrape": "abrasion",
  "Allergic reaction (not anaphylaxis)": "allergic_reaction",
  Amputation: "amputation",
  Anaphylaxis: "anaphylaxis",
  "Asthma / respiratory": "asthma",
  "Bite wound": "bite_wound",
  Bruise: "bruise",
  "Broken bone / fracture / dislocation": "broken_bone",
  "Burn / sunburn": "burn",
  Choking: "choking",
  Concussion: "concussion",
  "Crush / jam": "crush",
  "Cut / open wound": "cut",
  "Drowning (non-fatal)": "drowning",
  "Electric shock": "electric_shock",
  "Eye injury": "eye_injury",
  "Infectious disease (incl. gastrointestinal)": "infectious_disease",
  "High temperature": "high_temperature",
  "Ingestion / inhalation / insertion": "ingestion",
  "Internal injury / infection": "internal_injury",
  Poisoning: "poisoning",
  Rash: "rash",
  Respiratory: "respiratory",
  "Seizure / unconscious / convulsion": "seizure",
  "Sprain / swelling": "sprain",
  "Stabbing / piercing": "stabbing",
  Tooth: "tooth",
  "Venomous bite / sting": "venomous_bite",
  "Other (please specify)": "other",
};

export const NATURE_API_KEYS = Object.values(NATURE_API_MAP);

export function natureLabelsFromApiRecord(record = {}) {
  return NATURE_OPTIONS.filter((label) => Number(record[NATURE_API_MAP[label]]) === 1);
}
