export const ACCESS_OPTIONS = [
  { value: "1h", label: "1 Hour", ms: 60 * 60 * 1000 },
  { value: "4h", label: "4 Hours", ms: 4 * 60 * 60 * 1000 },
  { value: "8h", label: "8 Hours", ms: 8 * 60 * 60 * 1000 },
  { value: "1w", label: "1 Week", ms: 7 * 24 * 60 * 60 * 1000 },
  { value: "1m", label: "1 Month", ms: 30 * 24 * 60 * 60 * 1000 },
  { value: "1y", label: "1 Year", ms: 365 * 24 * 60 * 60 * 1000 },
];

export const initialStaff = [
  {
    id: "s1",
    name: "Aman21",
    email: "aman@gmail.com",
    contact: "1233337890",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s2",
    name: "admin",
    email: "admin@mykronicle.com",
    contact: "8909357490",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s3",
    name: "Jacob Marsh",
    email: "jacobmarsha@mydaire.com",
    contact: "1234567890",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s4",
    name: "rajat",
    email: "rj@gmail.com",
    contact: "8909355555",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s5",
    name: "Jack",
    email: "jack@gmail.com",
    contact: "2552552554",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s6",
    name: "Zayn Khan",
    email: "tabrezk294@gmail.com",
    contact: "8115345133",
    gender: "Male",
    avatar: "",
    centerId: "ct1",
    active: true,
    accessExpiresAt: new Date("2027-01-21T23:00:00").toISOString(),
  },
  {
    id: "s7",
    name: "Rahul Singh",
    email: "staff0111@example.com",
    contact: "9876543210",
    gender: "Male",
    avatar: "",
    centerId: "ct2",
    active: true,
    accessExpiresAt: null,
  },
  {
    id: "s8",
    name: "VVVVVVVV",
    email: "staff021@example.com",
    contact: "9876543210",
    gender: "Male",
    avatar: "",
    centerId: "ct3",
    active: true,
    accessExpiresAt: null,
  },
];