const AVATAR_POOL = [
  "https://i.pravatar.cc/100?img=12",
  "https://i.pravatar.cc/100?img=23",
  "https://i.pravatar.cc/100?img=34",
  "https://i.pravatar.cc/100?img=45",
  "https://i.pravatar.cc/100?img=56",
  "https://i.pravatar.cc/100?img=67",
  "https://i.pravatar.cc/100?img=8",
  "https://i.pravatar.cc/100?img=9",
];

export const EDUCATOR_POOL = [
  { id: "e1", name: "adil", avatar: AVATAR_POOL[0] },
  { id: "e2", name: "admin", avatar: AVATAR_POOL[1] },
  { id: "e3", name: "Aman21", avatar: AVATAR_POOL[2] },
  { id: "e4", name: "Amir", avatar: AVATAR_POOL[3] },
  { id: "e5", name: "Sarah Lee", avatar: AVATAR_POOL[4] },
  { id: "e6", name: "Mia Chen", avatar: AVATAR_POOL[5] },
  { id: "e7", name: "Daniel Park", avatar: AVATAR_POOL[6] },
  { id: "e8", name: "Priya Nair", avatar: AVATAR_POOL[7] },
];

export const STATUS_OPTIONS = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];

export const mockRoomsList = [
  {
    id: "r1",
    name: "test",
    status: "active",
    centreId: "c1",
    fromAge: 0,
    toAge: 5,
    capacity: 20,
    children: 2,
    educators: [EDUCATOR_POOL[4], EDUCATOR_POOL[5], EDUCATOR_POOL[6]],
  },
  {
    id: "r2",
    name: "test by apk",
    status: "active",
    centreId: "c1",
    fromAge: 0,
    toAge: 8,
    capacity: 25,
    children: 3,
    educators: [EDUCATOR_POOL[0], EDUCATOR_POOL[1]],
  },
  {
    id: "r3",
    name: "test by apk",
    status: "active",
    centreId: "c1",
    fromAge: 0,
    toAge: 9,
    capacity: 18,
    children: 0,
    educators: [],
  },
  {
    id: "r4",
    name: "Sunflower",
    status: "active",
    centreId: "c2",
    fromAge: 1,
    toAge: 4,
    capacity: 15,
    children: 8,
    educators: [EDUCATOR_POOL[2], EDUCATOR_POOL[3]],
  },
  {
    id: "r5",
    name: "Daisy",
    status: "inactive",
    centreId: "c2",
    fromAge: 2,
    toAge: 5,
    capacity: 12,
    children: 0,
    educators: [EDUCATOR_POOL[7]],
  },
  {
    id: "r6",
    name: "Tulip",
    status: "active",
    centreId: "c3",
    fromAge: 0,
    toAge: 6,
    capacity: 22,
    children: 5,
    educators: [EDUCATOR_POOL[4], EDUCATOR_POOL[7]],
  },
];